name: chek secrets

on:
  push:
    branches:
      - main

jobs:
  check_secret_job:
    runs-on: ubuntu-latest
    steps:
      - name: check_secret_step
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "il mio primo $MY_SECRET"
